---
#################
### K3s SETUP ###
#################

- name: Check if SELinux is installed
  find:
    paths: "/etc/selinux"
    hidden: false
    file_type: file
    patterns: "config"
    recurse: no
  register: selinux_result

- name: Configuring SELinux in permissive mode
  ansible.posix.selinux:
    policy: targeted
    state: permissive
  when: (selinux_result.files | length > 0)

- name: Ensure Firewalld/Iptables service are stopped
  service:
    name: "{{ item_firewalld_svc }}"
    state: stopped
    enabled: false
  loop:
    - firewalld
    - iptables
  loop_control:
    loop_var: item_firewalld_svc
  ignore_errors: yes

- name: Check if K3S is already installed
  stat:
    path: /usr/local/bin/k3s
  register: k3s_stat

- name: Install K3S if not installed or if variable 'k3s_reconfigure' is set to 'true'
  shell: |
    curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="{{ k3s_install_options }}" sh -s -
  when: not k3s_stat.stat.exists or k3s_reconfigure

- name: Start & Enable k3s systemd service
  systemd_service:
    name: k3s
    state: started
    enabled: true
    daemon_reload: true

- name: Replace server address in K3s kubeconfig with the instance ip
  replace:
    path: /etc/rancher/k3s/k3s.yaml
    regexp: 'https://127.0.0.1:6443'
    replace: "https://{{ k3s_kubeconfig_server }}:6443"

- name: Copy kubeconfig file locally as "{{ k3s_kubeconfig_local_path }}"
  ansible.builtin.fetch:
    src: "/etc/rancher/k3s/k3s.yaml"
    dest: "{{ k3s_kubeconfig_local_path }}"
    flat: yes
